# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('work', ['network', 'internet'])
    module.source = [
        'model/work-server.cc',
        'model/work-device-enforcer.cc',
        'helper/work-utils.cc',
        ]

    module_test = bld.create_ns3_module_test_library('work')
    module_test.source = [
        'test/work-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'work'
    headers.source = [
        'model/work-server.h',
        'model/work-device-enforcer.h',
        'helper/work-utils.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

